Fix/chat and articles
Leon-Art-EIP/Web pull request #66
Opened 2024-10-14 15:00 UTC by Vivant-Garrigues

- FIX affichage et modification des notifications par mail sur la page settings
- FIX thèmes non persistant sur certaines page
- FIX problème d'affichage des bandeau articles

2024-10-14 21:00 UTC, MariusNWK requested changes
Fix le build (``yarn build`` dans le terminal)

2024-10-15 14:25 UTC, Vivant-Garrigues commented
J'ai fix le problème de build. J'utilisais un IProfileUser à la place d'un IConnectedUser.

2024-10-16 06:55 UTC, MariusNWK requested changes

2024-10-16 06:55 UTC, MariusNWK commented on src/app/settings/page.tsx
> +  if (loading) return <div>Loading...</div>;
français

2024-10-16 06:55 UTC, MariusNWK commented on src/app/settings/page.tsx
> +      console.log("User: ", userId);
supprimer ce console.log

2024-10-16 06:57 UTC, MariusNWK commented
@Vivant-Garrigues le fichier package-lock.json apparaît quand tu fais ``npm install``. Fais ``yarn`` plutôt. Quand tu oublies et que tu fais ``npm install``, supprime le package-lock.json avant de push.
Enlève le stp

2024-10-16 10:20 UTC, Vivant-Garrigues commented
- Screen de chargement mis en français. J'ai également fais la modification à d'autres endroits du projet.
- Console.log supprimé
- package-lock.json supprimé

2024-10-25 09:48 UTC, MariusNWK approved these changes

2024-10-29 14:17 UTC, merged